name: Unit Tests and Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    name: ${{ matrix.platform }} Node ${{ matrix.node }} build/test
    strategy:
      matrix:
        node: [ 12, 10 ]
        platform: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      working-directory: ./packages/grpc-native-core

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: prepack
        working-directory: '${{env.working-directory}}'
        run: npm run prepack
      - name: test
        working-directory: '${{env.working-directory}}'
        run: npm run coverage
      - uses: actions/upload-artifact@v1
        working-directory: '${{env.working-directory}}'
        with:
          name: ${{ matrix.platform }}-${{ matrix.node }}
          path: build/Release/grpc_node.node
        if: github.ref == 'refs/heads/master'

  build-and-test-linux:
    strategy:
      matrix:
        node: [ 12, 10 ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/centos7-test
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/upload-artifact@v1
        with:
          name: linux-${{ matrix.node }}
          path: build/Release/grpc_node.node
        if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-16.04

  artifact:
    # if: github.ref == 'refs/heads/master'
    needs: [ build-and-test, build-and-test-linux ]
    runs-on: ubuntu-latest
    name: Building artifact
    env:
      working-directory: ./packages/grpc-native-core

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # download all of the built artifacts.
      - run: mkdir artifact
        working-directory: '${{env.working-directory}}'
      - uses: actions/download-artifact@v1
        with:
          name: linux-12
          path: artifact/linux-12
        working-directory: '${{env.working-directory}}'
      - uses: actions/download-artifact@v1
        with:
          name: linux-10
          path: artifact/linux-10
        working-directory: '${{env.working-directory}}'
      - uses: actions/download-artifact@v1
        with:
          name: macos-latest-12
          path: artifact/darwin-12
        working-directory: '${{env.working-directory}}'
      - uses: actions/download-artifact@v1
        with:
          name: macos-latest-10
          path: artifact/darwin-10
        working-directory: '${{env.working-directory}}'
        - uses: actions/download-artifact@v1
        with:
          name: windows-latest-12
          path: artifact/win32-12
        working-directory: '${{env.working-directory}}'
      - uses: actions/download-artifact@v1
        with:
          name: windows-latest-10
          path: artifact/win32-10
        working-directory: '${{env.working-directory}}'
      - name: pack artifact
        run: |
          echo "artifacts" && ls artifact
          mv index.js package.json artifact/
          cd artifact && npm pack | xargs -I '{}' mv {} ./grpc_node.tgz
      - uses: actions/upload-artifact@v1
        with:
          name: grpc_node.tgz
          path: artifact/grpc_node.tgz
        working-directory: '${{env.working-directory}}'
        # upload the un-tar'd version
      - uses: actions/upload-artifact@v1
        with:
          name: grpc_node
          path: artifact
        working-directory: '${{env.working-directory}}'

  artifact-test:
    if: github.ref == 'refs/heads/master'
    needs: [ artifact ]
    env:
      USE_ARTIFACT: 1
    strategy:
      matrix:
        platform: [ ubuntu-16.04, macos-latest, windows-latest ]
        node: [ 10, 12 ]
    name: ${{ matrix.platform }} Unit tests with artifact
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - uses: actions/download-artifact@v1
        with:
          name: grpc_node
          path: prebuilt
      - run: npm test
